# Generated by Django 5.2.11 on 2026-04-25 09:27

import core.models
import django.core.validators
import django.db.models.deletion
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('transfer_id', models.UUIDField(db_index=True)),
                ('recipient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('transfer_created', 'Transfer Created'), ('email_sent', 'Email Sent'), ('link_opened', 'Link Opened'), ('file_downloaded', 'File Downloaded'), ('transfer_deactivated', 'Transfer Deactivated'), ('transfer_expired', 'Transfer Expired'), ('files_deleted', 'Files Deleted')], max_length=30)),
                ('actor_type', models.CharField(choices=[('agent', 'Agent'), ('external', 'External')], max_length=10)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_transfer_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('sub', models.CharField(blank=True, help_text='Required. 255 characters or fewer. Letters, numbers, and @/./+/-/_/: characters only.', max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sub. This value may contain only letters, numbers, and @/./+/-/_/: characters.', regex='^[\\w.@+-:]+\\Z')], verbose_name='sub')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='identity email address')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='admin email address')),
                ('language', models.CharField(choices=[('fr-fr', 'French'), ('en-us', 'English')], default='fr-fr', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language')),
                ('timezone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='UTC', help_text='The timezone in which the user wants to see times.', use_pytz=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'core_user',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('expires_at', models.DateTimeField()),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deactivated', 'Deactivated')], default='active', max_length=16)),
                ('public_token', models.CharField(db_index=True, default=core.models._generate_public_token, help_text='Opaque token used in public download URLs. Populated at finalize time (= when the Transfer row is created).', max_length=64, unique=True)),
                ('sharing_mode', models.CharField(choices=[('email', 'Email'), ('link', 'Link')], default='link', max_length=5)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_transfer_draft',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('s3_key', models.CharField(max_length=512)),
                ('upload_id', models.CharField(blank=True, default='', help_text='S3 multipart upload id while the upload is in progress.', max_length=256)),
                ('upload_completed_at', models.DateTimeField(blank=True, help_text='Set once all parts have been uploaded and the multipart upload has been completed on S3.', null=True)),
                ('source_url', models.URLField(blank=True, default='', help_text='Public Drive permalink when the file was imported server-side rather than uploaded by the browser. Preserved after import completes for audit — the bytes live in our S3 like any other file once ``upload_completed_at`` is set.', max_length=2048)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.transferdraft')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.transfer')),
            ],
            options={
                'db_table': 'core_transfer_file',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('draft__isnull', True), ('transfer__isnull', False)), models.Q(('draft__isnull', False), ('transfer__isnull', True)), _connector='OR'), name='transferfile_exactly_one_parent')],
            },
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(max_length=254)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.transfer')),
            ],
            options={
                'db_table': 'core_transfer_recipient',
                'unique_together': {('transfer', 'email')},
            },
        ),
    ]
