# Generated by Django 5.1.8 on 2025-07-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='is_identity',
            field=models.BooleanField(default=True, help_text='Whether this mailbox identifies a person (i.e. is not an alias or a group)', verbose_name='is identity'),
        ),
    ]
