# Generated by Django 5.2.11 on 2026-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='notifications_completed_at',
            field=models.DateTimeField(blank=True, help_text="Set when ``send_recipient_invitations_task`` has run through every recipient (whether their delivery succeeded or not). The frontend polls this to know when to leave the 'sending…' state.", null=True),
        ),
    ]
