# Generated by Django 5.2.11 on 2026-04-08 18:51

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('transfer_id', models.UUIDField(db_index=True)),
                ('recipient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('transfer_created', 'Transfer Created'), ('email_sent', 'Email Sent'), ('link_opened', 'Link Opened'), ('password_attempt', 'Password Attempt'), ('file_downloaded', 'File Downloaded'), ('all_files_downloaded', 'All Files Downloaded'), ('transfer_revoked', 'Transfer Revoked'), ('transfer_expired', 'Transfer Expired'), ('files_deleted', 'Files Deleted')], max_length=30)),
                ('actor_type', models.CharField(choices=[('agent', 'Agent'), ('external', 'External')], max_length=10)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_transfer_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('public_token', models.CharField(db_index=True, default=core.models._generate_public_token, max_length=64, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('s3_key', models.CharField(max_length=512)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.transfer')),
            ],
            options={
                'db_table': 'core_transfer_file',
            },
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(max_length=254)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.transfer')),
            ],
            options={
                'db_table': 'core_transfer_recipient',
            },
        ),
    ]
