# Generated by Django 5.2.11 on 2026-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transfer_notifications_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.JSONField(blank=True, default=dict, help_text='Subset of OIDC userinfo kept for integrations (e.g. DeployCenter entitlements). Keys come from OIDC_STORE_CLAIMS.'),
        ),
    ]
