# Generated by Django 5.1.8 on 2025-07-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mailbox_is_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='summary',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='summary'),
        ),
    ]
