# Generated by Django 5.2.11 on 2026-04-24 11:15

from django.db import migrations, models


def backfill_deactivation_reason(apps, schema_editor):
    Transfer = apps.get_model('core', 'Transfer')
    # Rows that expired via the cron — map to the new unified DEACTIVATED
    # status with the 'expired' reason.
    Transfer.objects.filter(status='expired').update(
        status='deactivated',
        deactivation_reason='expired',
    )
    # Rows already DEACTIVATED before this PR had no deactivation_reason
    # column — they were all manual revocations.
    Transfer.objects.filter(status='deactivated', deactivation_reason__isnull=True).update(
        deactivation_reason='manual',
    )


def reverse_backfill_deactivation_reason(apps, schema_editor):
    Transfer = apps.get_model('core', 'Transfer')
    Transfer.objects.filter(status='deactivated', deactivation_reason='expired').update(
        status='expired',
        deactivation_reason=None,
    )
    Transfer.objects.filter(status='deactivated', deactivation_reason='manual').update(
        deactivation_reason=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transfer_notifications_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='auto_archive_on_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Manually deactivated'), ('expired', 'Expired'), ('first_download', 'Deactivated after first full download')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='pending_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_file_deletion', 'Pending file deletion'), ('deactivated', 'Deactivated')], default='active', max_length=24),
        ),
        migrations.RunPython(
            backfill_deactivation_reason,
            reverse_code=reverse_backfill_deactivation_reason,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='event_type',
            field=models.CharField(choices=[('transfer_created', 'Transfer Created'), ('email_sent', 'Email Sent'), ('link_opened', 'Link Opened'), ('file_downloaded', 'File Downloaded'), ('transfer_deactivated_manually', 'Transfer Deactivated Manually'), ('transfer_deactivated_after_first_download', 'Transfer Deactivated After First Download'), ('transfer_deactivated_after_expiry', 'Transfer Deactivated After Expiry'), ('file_deleted', 'File Deleted')], max_length=64),
        ),
    ]
