# Generated by Django 5.2.11 on 2026-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferevent_transfer_transferfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='upload_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set once all parts have been uploaded and the multipart upload has been completed on S3.', null=True),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='upload_id',
            field=models.CharField(blank=True, default='', help_text='S3 multipart upload id while the upload is in progress.', max_length=256),
        ),
    ]
