# Generated by Django 5.1.8 on 2025-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thread_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildomain',
            name='custom_attributes',
            field=models.JSONField(blank=True, default={}, help_text='Metadata to sync to the maildomain group in the identity provider.', verbose_name='Custom attributes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_attributes',
            field=models.JSONField(blank=True, default={}, help_text='Metadata to sync to the user in the identity provider.', verbose_name='Custom attributes'),
        ),
    ]
