# Generated by Django 5.2.11 on 2026-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transferfile_upload_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
