# Generated by Django 5.2.11 on 2026-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transferfile_scan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfile',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', help_text="Antivirus scan state. A file is only downloadable once it is CLEAN; the download path fails closed on anything else. Driven by the clamav file-scanner service's webhook callback.", max_length=10),
        ),
    ]
