# Generated by Django 5.1.8 on 2025-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maildomain_custom_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the label, used by AI to understand its purpose', max_length=255, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='label',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='Whether this label should be automatically applied by AI', verbose_name='auto labeling'),
        ),
        migrations.AlterField(
            model_name='maildomain',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata to sync to the maildomain group in the identity provider.', verbose_name='Custom attributes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata to sync to the user in the identity provider.', verbose_name='Custom attributes'),
        ),
    ]
