# Generated by Django 5.2.11 on 2026-06-23 09:21

from django.db import migrations, models


def grandfather_existing_files_clean(apps, schema_editor):
    """Existing *uploaded* files predate antivirus scanning — mark them CLEAN
    so they stay downloadable. Scope to ``upload_completed_at`` so an in-flight
    draft (upload not finished) keeps the PENDING default and is scanned for
    real when it later completes; otherwise it would slip through complete_upload
    as CLEAN, never scanned."""
    TransferFile = apps.get_model("core", "TransferFile")
    TransferFile.objects.filter(upload_completed_at__isnull=False).update(
        scan_status="clean"
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='scan_error_kind',
            field=models.CharField(blank=True, default='', help_text="Set only when scan_status is ERROR. 'transient' = an infrastructure failure that a retry may clear; 'file' = the file itself can't be scanned, so the user must remove it.", max_length=10),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='scan_job_id',
            field=models.CharField(blank=True, default='', help_text='Job id returned by the file-scanner service when the scan was submitted. Kept for traceability / debugging.', max_length=64),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('skipped', 'Skipped'), ('too_large', 'Too large to scan')], default='pending', help_text="Antivirus scan state. A file is downloadable when CLEAN or scan-exempt (SKIPPED / TOO_LARGE); the download path fails closed on anything else. Driven by the clamav file-scanner service's webhook callback.", max_length=10),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Per-file opaque token embedded in the scan callback URL. The scanner echoes it back; the webhook compares it (constant-time) before trusting the result. Generated when the scan is submitted.', max_length=64),
        ),
        migrations.RunPython(
            grandfather_existing_files_clean, reverse_code=noop_reverse
        ),
    ]
