# Generated by Django 5.2.11 on 2026-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transferfile_scan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='encryption_chunk_size',
            field=models.PositiveIntegerField(blank=True, help_text='Plaintext bytes per crypto chunk; ciphertext part on S3 is this + 28 bytes (12-byte IV + 16-byte GCM tag). Null only for legacy transfers created before encryption was mandatory.', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='encryption_key',
            field=models.CharField(blank=True, default='', help_text='URL-safe base64 of the AES-256 key (the same 43-char string used as the URL fragment). Populated only for non-confidential encrypted transfers; empty for confidential ones (key never reaches us) and legacy plaintext transfers.', max_length=64),
        ),
        migrations.AddField(
            model_name='transferdraft',
            name='encryption_chunk_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferdraft',
            name='encryption_key',
            field=models.CharField(blank=True, default='', help_text='URL-safe base64 of the AES-256 key, mirrored here at finalize so the Drive-import worker can encrypt server-fetched bytes without receiving the key through Celery kwargs. Populated only for non-confidential transfers; empty for confidential ones (key never reaches us). Dropped with the draft.', max_length=64),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='bytes_imported',
            field=models.PositiveBigIntegerField(default=0, help_text='Plaintext bytes streamed into S3 so far by ``import_drive_file_task``. Bumped after each S3 part upload; the finalize 202 poll exposes it so the frontend can render a progress bar rather than an opaque spinner. Stays 0 for browser uploads (client-side already knows its own progress).'),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='import_failed_at',
            field=models.DateTimeField(blank=True, help_text='Set when a server-side Drive import fails. The finalize poll surfaces this to the user (who removes the file and retries) instead of the import silently dropping the row.', null=True),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='import_started_at',
            field=models.DateTimeField(blank=True, help_text="Set the moment finalize enqueues a server-side Drive import, before the task creates the S3 multipart upload. Gates the finalize poll so a concurrent re-post can't enqueue the import twice.", null=True),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='plaintext_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Decoded file size before encryption. Null when the parent transfer is not encrypted — UIs should fall back to ``size``.', null=True),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='scan_submitted_at',
            field=models.DateTimeField(blank=True, help_text="Set when the file was handed to the scanner. Distinguishes 'PENDING, scan running' from 'PENDING, key not yet supplied', and keeps the finalize poll loop from re-submitting a scan already in flight.", null=True),
        ),
        migrations.AddIndex(
            model_name='transferfile',
            index=models.Index(condition=models.Q(('scan_status', 'pending')), fields=['scan_submitted_at'], name='transferfile_pending_scan_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('confidential', False), ('encryption_key', ''), _connector='OR'), name='transfer_confidential_has_no_key'),
        ),
    ]
