# Generated by Django 5.2.11 on 2026-04-16 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transfer_upload_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sharing_mode',
            field=models.CharField(choices=[('email', 'Email'), ('link', 'Link')], default='link', max_length=5),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sensitive',
            field=models.BooleanField(default=False, help_text='Reserved — the agent can flag a transfer as sensitive, but this flag has no runtime effect yet. Surfaced on the transfer detail for future product use.'),
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(max_length=254)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.transfer')),
            ],
            options={
                'db_table': 'core_transfer_recipient',
                'unique_together': {('transfer', 'email')},
            },
        ),
    ]
