# Generated by Django 5.1.11 on 2025-09-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_label_description_label_is_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxaccess',
            name='accessed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='accessed at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='draft_blob',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='core.blob'),
        ),
    ]
