# Generated by Django 5.2.11 on 2026-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transfer_sharing_mode_and_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='files_deleted_at',
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='event_type',
            field=models.CharField(choices=[('transfer_created', 'Transfer Created'), ('email_sent', 'Email Sent'), ('link_opened', 'Link Opened'), ('file_downloaded', 'File Downloaded'), ('transfer_revoked', 'Transfer Revoked'), ('transfer_expired', 'Transfer Expired'), ('files_deleted', 'Files Deleted')], max_length=30),
        ),
    ]
