# Generated by Django 5.2.11 on 2026-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_e2e_encryption_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='e2e_encrypted',
        ),
        migrations.RemoveField(
            model_name='transferdraft',
            name='e2e_encrypted',
        ),
        migrations.AddField(
            model_name='transfer',
            name='confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='encryption_key',
            field=models.CharField(blank=True, default='', help_text='URL-safe base64 of the AES-256 key (the same 43-char string used as the URL fragment). Populated only for non-confidential encrypted transfers; empty for confidential ones (key never reaches us) and legacy plaintext transfers.', max_length=64),
        ),
        migrations.AddField(
            model_name='transferfile',
            name='import_failed_at',
            field=models.DateTimeField(blank=True, help_text='Set when a server-side Drive import fails. The finalize poll surfaces this to the user (who removes the file and retries) instead of the import silently dropping the row.', null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='encryption_chunk_size',
            field=models.PositiveIntegerField(blank=True, help_text='Plaintext bytes per crypto chunk; ciphertext part on S3 is this + 28 bytes (12-byte IV + 16-byte GCM tag). Null only for legacy transfers created before encryption was mandatory.', null=True),
        ),
    ]
