# Generated by Django 5.2.11 on 2026-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transfer_e2e_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='import_started_at',
            field=models.DateTimeField(blank=True, help_text="Set the moment finalize enqueues a server-side Drive import, before the task creates the S3 multipart upload. Gates the finalize poll so a concurrent re-post can't enqueue the import twice.", null=True),
        ),
    ]
