# Generated by Django 5.2.11 on 2026-04-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transfer_files_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='password_hash',
        ),
    ]
