# Generated by Django 5.2.11 on 2026-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipient_token_and_download_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfile',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error'), ('skipped', 'Skipped'), ('too_large', 'Too large to scan'), ('unscannable', 'Could not be scanned')], default='pending', help_text="Antivirus scan state. A file is downloadable when CLEAN or scan-exempt (SKIPPED / TOO_LARGE / UNSCANNABLE); the download path fails closed on anything else. Driven by the clamav file-scanner service's webhook callback.", max_length=16),
        ),
    ]
