# Generated by Django 5.2.11 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transferfile_import_started_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('confidential', False), ('encryption_key', ''), _connector='OR'), name='transfer_confidential_has_no_key'),
        ),
    ]
