# Generated by Django 5.2.11 on 2026-04-21 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_transfer_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfile',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.transfer'),
        ),
        migrations.CreateModel(
            name='TransferDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_transfer_draft',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transferfile',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.transferdraft'),
        ),
        migrations.AddConstraint(
            model_name='transferfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('draft__isnull', True), ('transfer__isnull', False)), models.Q(('draft__isnull', False), ('transfer__isnull', True)), _connector='OR'), name='transferfile_exactly_one_parent'),
        ),
    ]
