# Generated by Django 5.1.12 on 2025-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messagetemplate_blob_maildomain_alter_blob_mailbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='has_archived',
            field=models.BooleanField(default=False, verbose_name='has archived'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'French')], default='en-us', help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language'),
        ),
    ]
