# Generated by Django 5.2.11 on 2026-04-21 22:52

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transferfile_transfer_transferdraft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='upload_completed_at',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='public_token',
            field=models.CharField(db_index=True, default=core.models._generate_public_token, help_text='Opaque token used in public download URLs. Populated at finalize time (= when the Transfer row is created).', max_length=64, unique=True),
        ),
    ]
