# Generated by Django 5.2.11 on 2026-04-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_transfer_upload_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Public Drive permalink when the file was imported server-side rather than uploaded by the browser. Preserved after import completes for audit — the bytes live in our S3 like any other file once ``upload_completed_at`` is set.', max_length=2048),
        ),
    ]
