# Generated by Django 5.2.11 on 2026-04-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transferfile_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sensitive',
        ),
    ]
