# Generated by Django 5.2.11 on 2026-04-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_revoke_to_deactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
