# Generated by Django 5.1.15 on 2026-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_messagetemplate_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='cid',
            field=models.CharField(blank=True, help_text='Content-ID for inline images', max_length=255, null=True, verbose_name='content ID'),
        ),
    ]
