# Generated by Django 5.2.11 on 2026-03-02 14:19
#
# This migration removes legacy columns that have been replaced by
# ThreadAccess.read_at and Thread.*_messaged_at fields (added in 0017).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_threadaccess_last_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='has_unread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_unread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
    ]
