"""Seed the database with transfers (and matching S3 objects) for local testing.

Builds N transfers split between active / deactivated, each with a small
random number of placeholder files actually uploaded to the dev object
storage so the download flow has bytes to serve. Intended for local dev
only — never run against shared environments.
"""

import random
import secrets
import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import timedelta

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from faker import Faker

from core import models
from core.enums import SharingMode, TransferStatus
from core.services.s3 import get_s3_client

User = get_user_model()
fake = Faker()


# ~256 bytes of dummy content reused across every seeded file. Keeping a
# single payload lets us bulk-PUT thousands of objects in seconds; each
# object still has a unique key, so per-file presigned downloads work.
_DUMMY_BODY = (
    b"This is a placeholder file generated by `make seed-transfers`. "
    b"It is not a real upload and exists only so the transfer's "
    b"download flow has bytes to serve.\n"
) * 4


class Command(BaseCommand):
    help = "Seed transfers (and per-file S3 objects) for local development."

    def add_arguments(self, parser):
        parser.add_argument(
            "--user-email",
            help="Owner email; defaults to the first user in the DB.",
        )
        parser.add_argument(
            "--count",
            type=int,
            default=1000,
            help="Total number of transfers to create (default 1000).",
        )
        parser.add_argument(
            "--active-ratio",
            type=float,
            default=0.5,
            help="Fraction of transfers left active (default 0.5).",
        )
        parser.add_argument(
            "--max-files-per-transfer",
            type=int,
            default=3,
            help="Upper bound on the random per-transfer file count (default 3).",
        )

    def handle(self, *args, **opts):
        email = opts["user_email"]
        if email:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist as e:
                raise CommandError(f"No user with email {email!r}") from e
        else:
            user = User.objects.order_by("created_at").first()
            if user is None:
                raise CommandError(
                    "No users in DB; run `make superuser` or sign in once first."
                )

        count = opts["count"]
        active_ratio = opts["active_ratio"]
        max_files = opts["max_files_per_transfer"]
        active_count = int(count * active_ratio)
        bucket = settings.TRANSFERS_BUCKET_NAME
        now = timezone.now()

        self.stdout.write(
            f"Seeding {count} transfers ({active_count} active, "
            f"{count - active_count} deactivated) for {user.email}…"
        )

        transfers = []
        for i in range(count):
            is_active = i < active_count
            created = now - timedelta(minutes=random.randint(0, 60 * 24 * 30))
            transfers.append(
                models.Transfer(
                    owner=user,
                    title=fake.sentence(nb_words=4).rstrip("."),
                    expires_at=created + timedelta(days=random.randint(1, 30)),
                    status=(
                        TransferStatus.ACTIVE
                        if is_active
                        else TransferStatus.DEACTIVATED
                    ),
                    deactivated_at=(
                        None
                        if is_active
                        else created + timedelta(minutes=random.randint(1, 60 * 24 * 7))
                    ),
                    sharing_mode=random.choice([SharingMode.LINK, SharingMode.EMAIL]),
                    public_token=secrets.token_urlsafe(32),
                )
            )
        models.Transfer.objects.bulk_create(transfers, batch_size=200)

        files = []
        keys = []
        for tr in transfers:
            for _ in range(random.randint(1, max_files)):
                key = f"transfers/{tr.id}/{uuid.uuid4()}/{fake.file_name()}"
                files.append(
                    models.TransferFile(
                        transfer=tr,
                        filename=fake.file_name(),
                        size=len(_DUMMY_BODY),
                        mime_type="text/plain",
                        s3_key=key,
                        upload_completed_at=now,
                    )
                )
                keys.append(key)
        models.TransferFile.objects.bulk_create(files, batch_size=500)

        self.stdout.write(f"Uploading {len(keys)} placeholder objects to S3…")
        s3 = get_s3_client()

        def _put(key):
            s3.put_object(Bucket=bucket, Key=key, Body=_DUMMY_BODY)

        # Cap workers at boto3's default urllib3 pool size (10) so we
        # don't spam ``Connection pool is full`` warnings on every PUT.
        with ThreadPoolExecutor(max_workers=8) as ex:
            for _ in ex.map(_put, keys):
                pass

        self.stdout.write(
            self.style.SUCCESS(
                f"Done — {len(transfers)} transfers, {len(files)} files."
            )
        )
